apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-host-path
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: "/tmp/persistent-volume"

