apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  volumes:
  - name: host-path
    persistentVolumeClaim:
      claimName: pvc-host-path
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: host-path
      mountPath: "/tmp/test"

