apiVersion: v1
kind: Pod
metadata:
  name: nginx-no-policy-pod
  labels:
    app: nginx-no-policy-app
spec:
  restartPolicy: Never
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
