apiVersion: v1
kind: Service
metadata:
  name: notes-service-service
spec:
  selector:
    app: notes-service
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001