apiVersion: v1
kind: Service
metadata:
  name: notes-service-service
spec:
  selector:
    app: notes-service
  type: LoadBalancer
  # currently minikube on windows requires kubectl port-forward service/notes-service-service 30001:8080 to access the service outside the cluster
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001