apiVersion: v1
kind: Service
metadata:
  name: nginx-no-policy-service
spec:
  type: NodePort
  selector:
    app: nginx-no-policy-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007
