apiVersion: v1
kind: Service
metadata:
  name: nginx-allow-ingress-policy-service
spec:
  type: NodePort
  selector:
    app: nginx-allow-ingress-policy-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30009
