networks:
  notes_service_network:

services:
  mongodb:
    image: "mongo:latest"
    container_name: "mongodb"
    ports:
      - "27017:27017"
    networks:
      - notes_service_network
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"

  notes-serrvice:
    image: "pawelslowikdev/notes-service:latest"
    container_name: "notes-service"
    ports:
      - "8080:8080"
    networks:
      - notes_service_network
    depends_on:
      - mongodb
    environment:
      MONGO_DB_USERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
      MONGO_DB_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"
      MONGO_DB_DATABASE: "admin"
      MONGO_DB_PORT: "27017"
      MONGO_DB_HOST: "mongodb"