spring:
  data:
    mongodb:
      username: ${MONGO_DB_USERNAME}
      password: ${MONGO_DB_PASSWORD}
      database: ${MONGO_DB_DATABASE}
      port: ${MONGO_DB_PORT}
      host: ${MONGO_DB_HOST}

management:
  endpoints:
    web:
      exposure:
        include: "env"


logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG