apiVersion: v1
kind: Pod
metadata:
  name: alpine-pod-service-account-vegetables
spec:
  serviceAccountName: service-account-vegetables
  restartPolicy: Never
  containers:
  - name: alpine
    image: alpine
    command: [ "/bin/sh", "-c"]
    args:
    - |
      TOKEN=$(cat ${TOKEN_PATH});
      apk add curl;
      curl -X GET ${API_CONFIGMAPS_URL}/configmap-fruits --cacert ${CACERT_PATH} --header "Authorization: Bearer ${TOKEN}"; 
      curl -X GET ${API_CONFIGMAPS_URL}/configmap-vegetables --cacert ${CACERT_PATH} --header "Authorization: Bearer ${TOKEN}"; 
    env:
    - name: API_CONFIGMAPS_URL
      value: "https://kubernetes.default.svc/api/v1/namespaces/default/configmaps"
    - name: TOKEN_PATH
      value: /var/run/secrets/kubernetes.io/serviceaccount/token
    - name: CACERT_PATH
      value: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt 
