apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-role-fruits
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  resourceNames: ["configmap-fruits"]
  verbs: ["get", "list"]
