apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: role-binding-fruits
subjects:
- kind: ServiceAccount
  name: service-account-fruits
roleRef:
  kind: ClusterRole 
  name: cluster-role-fruits
  apiGroup: rbac.authorization.k8s.io
