apiVersion: v1
kind: Pod
metadata:
  name: http-client
spec:
  restartPolicy: Never
  containers:
  - name: alpine
    image: alpine
    command: ["/bin/sh","-c"]
    args:
    - |
      apk add curl;
      nslookup external-service.default.svc.cluster.local;
      while true; do curl -v http-service.default.svc.cluster.local; sleep 5; done;
