apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
  - name: busybox
    image: busybox:1.28
    env:
    - name: USER_NAME
      valueFrom:
        configMapKeyRef:
          name: user
          key: username
    - name: USER_EMAIL
      valueFrom:
        configMapKeyRef:
          name: user
          key: email
    - name: LIKED_VEGETABLES 
      valueFrom:
        configMapKeyRef:
          name: vegetables
          key: liked
    envFrom:
    - configMapRef:
        name: fruits       
    args:
    - env
